audio_extension: pcm
transform_method: fbank
sample_rate: 16000
frame_length: 20
frame_shift: 10
n_mels: 80
normalize: True
del_silence: True
feature_extract_by: kaldi
freq_mask_para: 18
time_mask_num: 4
freq_mask_num: 2
spec_augment: True
input_reverse: false